import os
import sys
import yaml
import datetime
import subprocess
import re

class NotebookLMAgent:
    def __init__(self, name, notebook_id, role_description):
        self.name = name
        self.notebook_id = notebook_id
        self.role_description = role_description

    def query(self, topic):
        # In a real scenario, we would use an MCP client here.
        # Since we don't have the client library, we simulate the output.
        print(f"  > [{self.name}] Thinking about '{topic}'...")
        
        # Simulation Logic based on role
        if "Linguist" in self.name:
            return f"**Analysis of {topic}**: The Hebrew term 'Shalem' (שָׁלֵם) suggests wholeness or peace. In this context, it implies Jacob arrived safely."
        elif "Historian" in self.name:
            return f"**Context of {topic}**: Shechem was a significant city in the central hill country. Buying a field indicates a shift from nomadism to settlement."
        elif "Theologian" in self.name:
            return f"**Interpretation of {topic}**: From a Reformed perspective, Jacob's purchase of land demonstrates faith in the promise, though his delay at Shechem is often critiqued."
        
        return f"(Response from {self.name})"

def load_config(path="agent_config.yaml"):
    if not os.path.exists(path):
        print(f"Error: Config file {path} not found.")
        return None
    with open(path, 'r', encoding='utf-8') as f:
        return yaml.safe_load(f)

def run_research_pipeline(topic_verse):
    config = load_config()
    if not config: return

    linguist = NotebookLMAgent(**config['agents']['linguist'])
    historian = NotebookLMAgent(**config['agents']['historian'])
    theologian = NotebookLMAgent(**config['agents']['theologian'])

    print(f"\n=== 🔍 Starting Bible Research on: {topic_verse} ===")

    # 1. Research Phase
    ling_res = linguist.query(topic_verse)
    hist_res = historian.query(topic_verse)
    theol_res = theologian.query(topic_verse)

    # 2. Report Compilation
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d")
    report_title = f"Genesis Research: {topic_verse}"
    
    # Format for the EPUB generator (Header detection)
    report_content = f"""{report_title}
Date: {timestamp}

<제목 차례>
1. Linguistic Analysis
2. Historical Context
3. Theological Synthesis

1. Linguistic Analysis
{ling_res}

2. Historical Context
{hist_res}

3. Theological Synthesis
{theol_res}

[해설]
This report was generated by the Bible Research Agent pipeline.
"""

    safe_topic = "".join(x for x in topic_verse if x.isalnum() or x in " _-").replace(" ", "_")
    txt_filename = f"research_{safe_topic}.txt"
    epub_filename = f"research_{safe_topic}.epub"
    
    with open(txt_filename, "w", encoding="utf-8") as f:
        f.write(report_content)
    
    print(f"\n📄 Text Report Saved: {txt_filename}")

    # 3. Trigger EPUB Creation
    create_epub_dynamically(txt_filename, epub_filename, report_title)

def create_epub_dynamically(source_file, output_epub, title):
    print(f"\n=== 📘 Converting to EPUB: {output_epub} ===")
    
    ps1_template_path = "create_epub.ps1"
    if not os.path.exists(ps1_template_path):
        print("Error: create_epub.ps1 template not found.")
        return

    with open(ps1_template_path, "r", encoding="utf-8") as f:
        script_content = f.read()

    # Dynamic Replacement of Configuration
    # We replace the top section variables
    
    new_config = f"""
$OutputFile = "{output_epub}"
$Title = "{title}"
$Author = "Bible Research Agent"
$Language = "en"
$Uuid = [Guid]::NewGuid().ToString()
$Date = (Get-Date).ToString("yyyy-MM-dd")

# Source content
$SourceFiles = @(
    @{{ filename = "{source_file}"; title = "{title}"; id = "chap1" }}
)
"""
    # Regex to replace the original config block
    # We assume the config block starts at the top and goes until the helper functions or some marker.
    # A simple way is to replace specific variable assignments if we can find them.
    # But replacing the whole block is safer if we know the structure.
    # Let's try replacing specific lines.
    
    script_content = re.sub(r'\$OutputFile = ".*?"', f'$OutputFile = "{output_epub}"', script_content)
    script_content = re.sub(r'\$Title = ".*?"', f'$Title = "{title}"', script_content)
    
    # Replacing the SourceFiles array is trickier with regex because it spans multiple lines.
    # We will look for "$SourceFiles = @(" and the closing ")"
    
    # Robust approach: Prepend the new config arguments and REMOVE the old assignments?
    # No, PowerShell executes top-down. If we Append new assignments AFTER the old ones, they win?
    # But the functions use global vars or passed params?
    # In the script, variables are global.
    # Let's write a wrapper script that includes the original functions but changes the logic?
    # Easier: Just replace the specific hardcoded lines we know exist since we wrote them.
    
    # Hard replacement of the specific block we know is there
    source_files_pattern = r'\$SourceFiles = @\(\s+@\{.*?\}\s+\)'
    new_source_files = f'$SourceFiles = @(\n    @{{ filename = "{source_file}"; title = "{title}"; id = "chap1" }}\n)'
    
    script_content = re.sub(source_files_pattern, new_source_files, script_content, flags=re.DOTALL)

    # Save temporary runner script
    temp_script = "temp_research_epub.ps1"
    with open(temp_script, "w", encoding="utf-8") as f:
        f.write(script_content)
        
    # Execution
    try:
        cmd = ["powershell", "-NoProfile", "-ExecutionPolicy", "Bypass", "-File", temp_script]
        result = subprocess.run(cmd, capture_output=True, text=True)
        
        if result.returncode == 0:
            print("✅ EPUB Generation Successful!")
            print(f"   Output: {output_epub}")
        else:
            print("❌ EPUB Generation Failed:")
            print(result.stderr)
            print(result.stdout)
            
    except Exception as e:
        print(f"Error running PowerShell: {e}")
    finally:
        if os.path.exists(temp_script):
            os.remove(temp_script)

if __name__ == "__main__":
    if len(sys.argv) > 1:
        topic = " ".join(sys.argv[1:])
    else:
        topic = "Genesis 33:18-20"
        
    run_research_pipeline(topic)
