
param([string]$Topic = "Genesis 33:18-20")

# Setup console encoding to UTF8 to avoid display issues
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8

Write-Host "=== 🔍 Starting Bible Research on: $Topic ===" -ForegroundColor Cyan

# 1. Load Configuration
$ConfigFile = "agent_config.yaml"
if (-not (Test-Path $ConfigFile)) {
    Write-Error "Config file not found."
    exit
}

$ConfigContent = Get-Content $ConfigFile -Raw -Encoding UTF8

function Get-NotebookId {
    param($Role)
    # Search for the block using single-line mode (?s)
    $Pattern = "(?s)$Role.*?notebook_id:\s*[""']?([a-zA-Z0-9-]+)[""']?"
    if ($ConfigContent -match $Pattern) {
        return $matches[1]
    }
    return "UNKNOWN"
}

$LinguistId = Get-NotebookId "linguist"
$HistorianId = Get-NotebookId "historian"
$TheologianId = Get-NotebookId "theologian"

Write-Host "Loaded Agents from Config:"
Write-Host " - Linguist ID: $LinguistId" -ForegroundColor Gray
Write-Host " - Historian ID: $HistorianId" -ForegroundColor Gray
Write-Host " - Theologian ID: $TheologianId" -ForegroundColor Gray

# 2. Simulate Agent Research
function Query-Agent {
    param($Name, $Topic)
    Write-Host "  > [$Name] Analyzing..." -ForegroundColor Green
    Start-Sleep -Seconds 1
    
    if ($Name -match "Linguist") {
        return "**Analysis of $Topic**: The Hebrew syntax uses the 'waw-consecutive'. Key term 'Shalem' (Gen 33:18) is disputed: safely vs. Salem."
    }
    elseif ($Name -match "Historian") {
        return "**Context of $Topic**: Shechem is a strategic valley. Jacob's purchase of land (v.19) establishes legal rights in Canaan."
    }
    elseif ($Name -match "Theologian") {
        return "**Interpretation of $Topic**: Reformed theology views this as partial fulfillment of the promise, despite Jacob's delay."
    }
    return "(Response from $Name)"
}

$LingRes = Query-Agent "Linguist Agent" $Topic
$HistRes = Query-Agent "Historian Agent" $Topic
$TheolRes = Query-Agent "Theologian Agent" $Topic

# 3. Report Compilation
$Date = (Get-Date).ToString("yyyy-MM-dd")
$ReportTitle = "Genesis Research: $Topic"

$ReportContent = @"
$ReportTitle
Date: $Date

<제목 차례>
1. Linguistic Analysis
2. Historical Context
3. Theological Synthesis

1. Linguistic Analysis
$LingRes

2. Historical Context
$HistRes

3. Theological Synthesis
$TheolRes

[해설]
This report was generated by the Bible Research Agent pipeline using NotebookLM Agents.
"@

# Filename handling
$SafeTopic = ($Topic -replace "[^a-zA-Z0-9]", "_") -replace "_+", "_"
$TxtFileName = "research_$SafeTopic.txt"
$EpubFileName = "research_$SafeTopic.epub"

Set-Content -Path $TxtFileName -Value $ReportContent -Encoding UTF8
Write-Host "`n📄 Text Report Saved: $TxtFileName" -ForegroundColor Yellow

# 4. Trigger EPUB Creation
Write-Host "`n=== 📘 Converting to EPUB: $EpubFileName ===" -ForegroundColor Cyan

$TemplateScript = "create_epub.ps1"
if (-not (Test-Path $TemplateScript)) {
    Write-Error "Template script create_epub.ps1 not found."
    exit
}

# CRITICAL: Read logic template with UTF8
$ScriptContent = Get-Content $TemplateScript -Raw -Encoding UTF8

# Robust Replacement: Split at StyleCSS
$SplitMarker = '$StyleCss = @"'
$Parts = $ScriptContent -split [regex]::Escape($SplitMarker)

if ($Parts.Count -lt 2) {
    Write-Error "Could not find StyleCSS marker."
    exit
}

$NewConfig = @"
# Generated Config
`$OutputFile = "$EpubFileName"
`$Title = "$ReportTitle"
`$Author = "Bible Research Agent"
`$Language = "en"
`$Uuid = [Guid]::NewGuid().ToString()
`$Date = (Get-Date).ToString("yyyy-MM-dd")

# Source content
`$SourceFiles = @(
    @{ filename = "$TxtFileName"; title = "$ReportTitle"; id = "chap1" }
)

$SplitMarker
"@

$FinalScript = $NewConfig + $Parts[1]
$TempScript = "temp_research_epub.ps1"
Set-Content -Path $TempScript -Value $FinalScript -Encoding UTF8

# Execute
try {
    Write-Host "Invoking EPUB Generator..."
    & ".\$TempScript"
}
finally {
    if (Test-Path $TempScript) { Remove-Item $TempScript }
}

Write-Host "`n✅ Pipeline Completed." -ForegroundColor Green
